### ISSUE TITLE
How do I validate the textarea

### ISSUE THREAD

**Issue by jrdn91** [ragnarpeterson/ember-text-limit#1]
I'm trying to figure out how to see if the textarea is over the count and if it is not allow it to save to the database.

In my controller I have this to get and save the values to my firebase backend

```
var newFlyer = this.store.createRecord('flyer', {
    firstName: this.get('firstName'),
    lastName: this.get('lastName'),
    location: this.get('location'),
    jobTitle: this.get('jobTitle'),
    companyName: this.get('companyName'),
    timeSpent: this.get('timeSpent'),
    blurb: this.get('blurb'),
    image: this.get('image'),
    croppedImage: this.get('finalCroppedImage')
});
newFlyer.save();
```

How can I check if the textarea is over the count? I see there is a property called over but I can't seem to get at that from my controller.

**Comment by jasonkriss** [comment]
When I created this, i primarily just wanted to display a count to the user while they are typing. I didn't really mean for it to be used for validation purposes. For that reason, there isn't really an easy to do what you are trying to do. I'd recommend just manually checking this in you controller prior to calling `this.store.createRecord`. Sorry I don't have a better answer for you! Let me know if you have any other questions.
